version: "3.9"

services:
  astro-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge